spring:
  application:
    name: backend

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
    path: /api/swagger-ui.html
